# Generated by Django 6.1.1 on 2026-09-22 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlyingSite',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('lat', models.FloatField(help_text='Launch latitude; round to 2 decimals for Windy (~1 km).', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(help_text='Launch longitude; round to 2 decimals for Windy.', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('elevation_m', models.FloatField(blank=True, help_text='Approx launch elevation for model elevation sanity check.', null=True)),
                ('allowed_wind_sectors', models.JSONField(default=list, help_text='e.g. [{"from": 337.5, "to": 67.5, "wrap": true}]')),
                ('wind_ideal_min_kmh', models.FloatField(default=5.0)),
                ('wind_ideal_max_kmh', models.FloatField(default=15.0)),
                ('wind_max_kmh', models.FloatField(default=20.0)),
                ('gust_max_kmh', models.FloatField(default=30.0)),
                ('gust_ratio_max', models.FloatField(default=1.6)),
                ('day_hour_start', models.PositiveSmallIntegerField(default=7)),
                ('day_hour_end', models.PositiveSmallIntegerField(default=18)),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64)),
                ('forecast_models', models.JSONField(default=list, help_text='Preferred forecast models, e.g. ["icon","iconEu","gfs"]')),
                ('require_model_agreement', models.BooleanField(default=True, help_text='If true, YES only when ≥2 models agree.')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32)),
                ('source', models.CharField(default='node', help_text='node | point_forecast | open_meteo', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('model_elevation_m', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_hours', models.JSONField(default=list, help_text='List of normalized hour observations.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_caches', to='sites.flyingsite')),
            ],
            options={
                'ordering': ['site_id', 'model'],
                'unique_together': {('site', 'model')},
            },
        ),
    ]
